---
apiVersion: v1
kind: Pod
metadata:
  name: mongo
  labels:
    components: mongo
spec:
  containers:
    - name: mongo
      image: mongo
      ports:
        - containerPort: 5435
      resources:
        requests:
          cpu: "250m"
          memory: "250Mi"
        limits:
          cpu: "500m"
          memory: "256Mi"


      env:
        - name: mongosecret
          valueFrom:
            secretKeyRef:
              name: my-secret
              key: secretkey1
        - name: myconfig-map
          valueFrom:
            configMapKeyRef:
              key: key1
              name: my-configmap




