apiVersion: apps/v1
kind: Deployment
metadata:
  name: react-deployment
spec:
  selector:
    matchLabels:
      components: React
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate


  template:
    metadata:
      name: react-frontend
      labels:
        components: React

    spec:
      containers:
        - name: react-frontend
          image: judrin/react-frontend
          ports:
            - containerPort: 80
          command: ['sh','-c','while true: do echo logs data > output/output.log:sleep 5:done']
          resources:
            requests:
              cpu: "250m"
              memory: "250Mi"
            limits:
              cpu: "500"
              memory: "256Mi"
          volumeMounts:
            - mountPath: /output
              name: shared-storage
        - name: redis
          image: redis:latest


          ports:
            - containerPort: 6379
          volumeMounts:
            - mountPath: /var/lib/redis/data
              name: shared-storage
              subPath: redis
      volumes:
        - name: shared-storage
          persistentVolumeClaim:
            claimName: pvc1
  replicas: 5
  minReadySeconds: 300

