apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv1
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ssd

  capacity:
    storage: 1Gi



  persistentVolumeReclaimPolicy: Retain
  awsElasticBlockStore:
    volumeID: vol-027c7d7b1d91892c0





