apiVersion: v1
kind: Pod
metadata:
  name: react-frontend
  labels:
    components: React

spec:



  containers:
    - name: react-frontend
      image: judrin/react-frontend
      ports:
        - containerPort: 80
 

