apiVersion: apps/v1
kind: Deployment
metadata:
  name: react-deployment
spec:
  selector:
    matchLabels:
      components: React
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate


  template:
    metadata:
      name: react-frontend
      labels:
        components: React

    spec:
      containers:
        - name: react-frontend
          image: judrin/react-frontend
          ports:
            - containerPort: 80
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: postgress storage
              subPath: postgres
      volumes:
        - name: postgress storage
          persistentVolumeClaim:
            claimName: pvc1
  replicas: 5
  minReadySeconds: 300

