---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jenkins-deployment
spec:
  selector:
    matchLabels:
      components: jenkins
  template:
    metadata:
      name: jenkins
      labels:
        components: jenkins
    spec:
      containers:
        - name: jenkins
          image: jenkins/jenkins:lts-jdk11
          ports:
            - containerPort: 8080
          volumeMounts:
            - name: jenkins-home
              mountPath: /var/jenkins-home
      volumes:
        - name: jenkins-home
          emptyDir: { }


  replicas: 1